# 코어 자스립트

## 프로미스와 async, await

### 콜백

```javascript
const func = (error, callback) => {
  if (!error) {
    callback()
  }
}
```

### 프로미스

```javascript
new Promise(function(resolve, reject) => {
  resolve(/* if success, result  */)

  reject(/* if failed, error  */)
})
promise.then(
  (result) =>  {}, /* 에러 발생 시 처리 불가, 내부 선언 필요 */
  (error) => {},
)
promise
  .then((result) => {})
  .catch((error) => {})
  .finally(() => {})
```
- 자바스크립트 내부 콜백인 `Promise`
  - `[state]`: `pending(보류, 처리중)`, `fulfilled`, `rejected`
  - `[result]`: `undefined`, `result`, `error`
- **성공** 또는 **실패**만 존재

### 프로미스 체이닝

> `thenable` : `.then()` 메서드를 갖는 객체

```javascript
new Promise()
  .then(() => {})
  .then(() => {})
  /* ... */
  .catch(() => {})
  .catch(() => {})
  /* ... */
  .finally(() => {})
fetch(/* URL */)
  .then((res) => res.json())
  .then((json) => console.log(json))
  .catch(() => {})
  .finally(() => {})
```

### 프로미스와 에러 핸들링

- 프로미스 거부 시 가까운 `.catch` 실행
- **암시적 `try..catch`** 를 갖고 있음 
  - 동기적인 에러 처리
- `.catch` 실행 후 가까운 `.then` 실행
  - **에러 발생 시 가까운 `.catch` 실행**
- 🚨`.catch` 없는 에러 발생은 끔찍하게 **전역 에러(unhandledrejection**[^1] 발생🚨
```javascript
window.addEventListener('unhandledrejection', (event) => {})
```

### 프로미스 API

```javascript
/**
 * 하나 실패 시 모두 실패
 */
Promise
  .all([...new Promise()])
  .then(() => {})
  .catch(() => {})

/**
 * 최소 하나 성공 시 성공
 */
Promise
  .allSettled([... new Promise()])
  .then(() => {})
  .catch(() => {})

/**
 * 가장 빠른 성공 또는 실패
 */
Promise
  .race([... new Promise()])
  .then(() => {})
  .catch(() => {})
```

### 마이크로태스크

- 비동기 작업은 `PromiseJobs` 라는 내부 큐(V8: 마이크로태스트 큐)에서 처리
  - FIFO
- 처리되지 못한 거부(`unhandledrejection`)는 마이크로 태스크 큐 끝에서 에러가 처리되지 못할 때 발생

### async와 await

- 함수 앞 `async`를 붙이면 항상 `Promise` 반환
- `await`은 `Promise`가 처리될 때까지 대기 후 반환(시각적 동기 처리)
- `await`은 `thenable` 객체를 받을 수 있음
  - `.then` 실행 후 반환
- `try..catch` 사용으로 에러 처리



[^1]: https://html.spec.whatwg.org/multipage/webappapis.html#unhandled-promise-rejections
